### PR TITLE
Upgrade to Swift 5.0 and add SPM support

### PR DESCRIPTION
**Pull request by zachstegall**

### CODE REVIEW

**Review by g-mark — CHANGES_REQUESTED** [review]
Thanks for bringing this up to date, @zachstegall !

I think we can remove the starter comments in the `Package.swift`, file.  Otherwise, looks great!

**Comment by zachstegall** [comment]
Thanks, will do!

**Comment by zachstegall** [comment]
@g-mark Would I need to update the `.swift-version` as well?

**Comment by zachstegall** [comment]
Hey @g-mark . Anything else you need from me?

**Review by g-mark — APPROVED** [review]
@zachstegall Nope, looks good - thanks for keeping me honest!

**Comment by zachstegall** [comment]
Great! Thanks!

**Pull request merged**
